export const doc: string[] = [];

doc.push(`
## Media Queries

Metrics are current as of July 2024, via: https://gs.statcounter.com/screen-resolution-stats.

To use a media query, prefix the property with the media-query-key.

### Default

- The default should be considered the smallest size, so there is no media query for it. It captures min-widths from 360px to 428px (35.32% marketshare)
- Targets: 360x640, 360x760, 360x780, 360x800, 375x667, 375x812, 385x854, 390x844, 393x851, 393x873, 412x892, 412x915, 414x896, 428x926.
- Prefix: none

### Small

- For min-widths of 430px to 1279px (2.77% marketshare). 
- Targets: 1280x720.
- Prefix: "media-min-width-430px"

### Medium

- For min widths of 1280px to 1599px (12.43% marketshare). 
- Targets: 1366x768, 1440x900, 1536x864.
- Prefix: ".media-min-width-1280px--"

### Large

- For min widths of 1600px to 1919px (1.17% marketshare). 
- Targets: 1600x900.
- Prefix: ".media-min-width-1600px--"

### Extra-Large

- For min widths of 1920px and up (9.24% marketshare). 
- Targets: 1920x1080.
- Prefix: ".media-min-width-1920px--"
`);
// TODO: Use arrays instead of objects
export const mediaQueries = [
    { '': '' }, // Placeholder, don't remove
    { 'media-min-width-430px': '@media (min-width: 430px)' },
    { 'media-min-width-1280px': '@media (min-width: 1280px)' },
    { 'media-min-width-1600px': '@media (min-width: 1600px)' },
    { 'media-min-width-1920px': '@media (min-width: 1920px)' },
];

doc.push(`
## Global Values

Every property gets the global values. For example, if your property is ''.background-color-*'', you will also have {{exampleGlobalValues}}.
`);
export const globalValues = [
    'initial',
    'inherit',
    'unset',
    'revert',
    'revert-layer',
];

doc.push(`
## Colors

You can use any of the HTML named colors by prefixing the name to a color property. For example, ''.background-color-aliceblue''. This also includes, currentcolor, and transparent.

{{namedColorReference}}

Hellwind also bundles the Material UI v3 colors. Use ''.background-color-mui-amber-100'', for example. Here is the full list:

{{muiColorReference}}
`);
export const colors = [
    'currentcolor',
    'transparent',
    'aliceblue',
    'antiquewhite',
    'aqua',
    'aquamarine',
    'azure',
    'beige',
    'bisque',
    'black',
    'blanchedalmond',
    'blue',
    'blueviolet',
    'brown',
    'burlywood',
    'cadetblue',
    'chartreuse',
    'chocolate',
    'coral',
    'cornflowerblue',
    'cornsilk',
    'crimson',
    'cyan',
    'darkblue',
    'darkcyan',
    'darkgoldenrod',
    'darkgray',
    'darkgreen',
    'darkgrey',
    'darkkhaki',
    'darkmagenta',
    'darkolivegreen',
    'darkorange',
    'darkorchid',
    'darkred',
    'darksalmon',
    'darkseagreen',
    'darkslateblue',
    'darkslategray',
    'darkslategrey',
    'darkturquoise',
    'darkviolet',
    'deeppink',
    'deepskyblue',
    'dimgray',
    'dimgrey',
    'dodgerblue',
    'firebrick',
    'floralwhite',
    'forestgreen',
    'fuchsia',
    'gainsboro',
    'ghostwhite',
    'gold',
    'goldenrod',
    'gray',
    'green',
    'greenyellow',
    'grey',
    'honeydew',
    'hotpink',
    'indianred',
    'indigo',
    'ivory',
    'khaki',
    'lavender',
    'lavenderblush',
    'lawngreen',
    'lemonchiffon',
    'lightblue',
    'lightcoral',
    'lightcyan',
    'lightgoldenrodyellow',
    'lightgray',
    'lightgreen',
    'lightgrey',
    'lightpink',
    'lightsalmon',
    'lightseagreen',
    'lightskyblue',
    'lightslategray',
    'lightslategrey',
    'lightsteelblue',
    'lightyellow',
    'lime',
    'limegreen',
    'linen',
    'magenta',
    'maroon',
    'mediumaquamarine',
    'mediumblue',
    'mediumorchid',
    'mediumpurple',
    'mediumseagreen',
    'mediumslateblue',
    'mediumspringgreen',
    'mediumturquoise',
    'mediumvioletred',
    'midnightblue',
    'mintcream',
    'mistyrose',
    'moccasin',
    'navajowhite',
    'navy',
    'oldlace',
    'olive',
    'olivedrab',
    'orange',
    'orangered',
    'orchid',
    'palegoldenrod',
    'palegreen',
    'paleturquoise',
    'palevioletred',
    'papayawhip',
    'peachpuff',
    'peru',
    'pink',
    'plum',
    'powderblue',
    'purple',
    'rebeccapurple',
    'red',
    'rosybrown',
    'royalblue',
    'saddlebrown',
    'salmon',
    'sandybrown',
    'seagreen',
    'seashell',
    'sienna',
    'silver',
    'skyblue',
    'slateblue',
    'slategray',
    'slategrey',
    'snow',
    'springgreen',
    'steelblue',
    'tan',
    'teal',
    'thistle',
    'tomato',
    'turquoise',
    'violet',
    'wheat',
    'white',
    'whitesmoke',
    'yellow',
    'yellowgreen',
    { 'mui-amber-100': '#ffecb3' },
    { 'mui-amber-200': '#ffe082' },
    { 'mui-amber-300': '#ffd54f' },
    { 'mui-amber-400': '#ffca28' },
    { 'mui-amber-50': '#fff8e1' },
    { 'mui-amber-500': '#ffc107' },
    { 'mui-amber-600': '#ffb300' },
    { 'mui-amber-700': '#ffa000' },
    { 'mui-amber-800': '#ff8f00' },
    { 'mui-amber-900': '#ff6f00' },
    { 'mui-amber-a100': '#ffe57f' },
    { 'mui-amber-a200': '#ffd740' },
    { 'mui-amber-a400': '#ffc400' },
    { 'mui-amber-a700': '#ffab00' },
    { 'mui-blue-100': '#bbdefb' },
    { 'mui-blue-200': '#90caf9' },
    { 'mui-blue-300': '#64b5f6' },
    { 'mui-blue-400': '#42a5f5' },
    { 'mui-blue-50': '#e3f2fd' },
    { 'mui-blue-500': '#2196f3' },
    { 'mui-blue-600': '#1e88e5' },
    { 'mui-blue-700': '#1976d2' },
    { 'mui-blue-800': '#1565c0' },
    { 'mui-blue-900': '#0d47a1' },
    { 'mui-blue-a100': '#82b1ff' },
    { 'mui-blue-a200': '#448aff' },
    { 'mui-blue-a400': '#2979ff' },
    { 'mui-blue-a700': '#2962ff' },
    { 'mui-blue-gray-100': '#cfd8dc' },
    { 'mui-blue-gray-200': '#b0bec5' },
    { 'mui-blue-gray-300': '#90a4ae' },
    { 'mui-blue-gray-400': '#78909c' },
    { 'mui-blue-gray-50': '#eceff1' },
    { 'mui-blue-gray-500': '#607d8b' },
    { 'mui-blue-gray-600': '#546e7a' },
    { 'mui-blue-gray-700': '#455a64' },
    { 'mui-blue-gray-800': '#37474f' },
    { 'mui-blue-gray-900': '#263238' },
    { 'mui-blue-gray-a100': '#cfd8dc' },
    { 'mui-blue-gray-a200': '#b0bec5' },
    { 'mui-blue-gray-a400': '#78909c' },
    { 'mui-blue-gray-a700': '#455a64' },
    { 'mui-brown-100': '#d7ccc8' },
    { 'mui-brown-200': '#bcaaa4' },
    { 'mui-brown-300': '#a1887f' },
    { 'mui-brown-400': '#8d6e63' },
    { 'mui-brown-50': '#efebe9' },
    { 'mui-brown-500': '#795548' },
    { 'mui-brown-600': '#6d4c41' },
    { 'mui-brown-700': '#5d4037' },
    { 'mui-brown-800': '#4e342e' },
    { 'mui-brown-900': '#3e2723' },
    { 'mui-brown-a100': '#d7ccc8' },
    { 'mui-brown-a200': '#bcaaa4' },
    { 'mui-brown-a400': '#8d6e63' },
    { 'mui-brown-a700': '#5d4037' },
    { 'mui-cyan-100': '#b2ebf2' },
    { 'mui-cyan-200': '#80deea' },
    { 'mui-cyan-300': '#4dd0e1' },
    { 'mui-cyan-400': '#26c6da' },
    { 'mui-cyan-50': '#e0f7fa' },
    { 'mui-cyan-500': '#00bcd4' },
    { 'mui-cyan-600': '#00acc1' },
    { 'mui-cyan-700': '#0097a7' },
    { 'mui-cyan-800': '#00838f' },
    { 'mui-cyan-900': '#006064' },
    { 'mui-cyan-a100': '#84ffff' },
    { 'mui-cyan-a200': '#18ffff' },
    { 'mui-cyan-a400': '#00e5ff' },
    { 'mui-cyan-a700': '#00b8d4' },
    { 'mui-deep-orange-100': '#ffccbc' },
    { 'mui-deep-orange-200': '#ffab91' },
    { 'mui-deep-orange-300': '#ff8a65' },
    { 'mui-deep-orange-400': '#ff7043' },
    { 'mui-deep-orange-50': '#fbe9e7' },
    { 'mui-deep-orange-500': '#ff5722' },
    { 'mui-deep-orange-600': '#f4511e' },
    { 'mui-deep-orange-700': '#e64a19' },
    { 'mui-deep-orange-800': '#d84315' },
    { 'mui-deep-orange-900': '#bf360c' },
    { 'mui-deep-orange-a100': '#ff9e80' },
    { 'mui-deep-orange-a200': '#ff6e40' },
    { 'mui-deep-orange-a400': '#ff3d00' },
    { 'mui-deep-orange-a700': '#dd2c00' },
    { 'mui-deep-purple-100': '#d1c4e9' },
    { 'mui-deep-purple-200': '#b39ddb' },
    { 'mui-deep-purple-300': '#9575cd' },
    { 'mui-deep-purple-400': '#7e57c2' },
    { 'mui-deep-purple-50': '#ede7f6' },
    { 'mui-deep-purple-500': '#673ab7' },
    { 'mui-deep-purple-600': '#5e35b1' },
    { 'mui-deep-purple-700': '#512da8' },
    { 'mui-deep-purple-800': '#4527a0' },
    { 'mui-deep-purple-900': '#311b92' },
    { 'mui-deep-purple-a100': '#b388ff' },
    { 'mui-deep-purple-a200': '#7c4dff' },
    { 'mui-deep-purple-a400': '#651fff' },
    { 'mui-deep-purple-a700': '#6200ea' },
    { 'mui-green-100': '#c8e6c9' },
    { 'mui-green-200': '#a5d6a7' },
    { 'mui-green-300': '#81c784' },
    { 'mui-green-400': '#66bb6a' },
    { 'mui-green-50': '#e8f5e9' },
    { 'mui-green-500': '#4caf50' },
    { 'mui-green-600': '#43a047' },
    { 'mui-green-700': '#388e3c' },
    { 'mui-green-800': '#2e7d32' },
    { 'mui-green-900': '#1b5e20' },
    { 'mui-green-a100': '#b9f6ca' },
    { 'mui-green-a200': '#69f0ae' },
    { 'mui-green-a400': '#00e676' },
    { 'mui-green-a700': '#00c853' },
    { 'mui-grey-100': '#f5f5f5' },
    { 'mui-grey-200': '#eeeeee' },
    { 'mui-grey-300': '#e0e0e0' },
    { 'mui-grey-400': '#bdbdbd' },
    { 'mui-grey-50': '#fafafa' },
    { 'mui-grey-500': '#9e9e9e' },
    { 'mui-grey-600': '#757575' },
    { 'mui-grey-700': '#616161' },
    { 'mui-grey-800': '#424242' },
    { 'mui-grey-900': '#212121' },
    { 'mui-grey-a100': '#f5f5f5' },
    { 'mui-grey-a200': '#eeeeee' },
    { 'mui-grey-a400': '#bdbdbd' },
    { 'mui-grey-a700': '#616161' },
    { 'mui-indigo-100': '#c5cae9' },
    { 'mui-indigo-200': '#9fa8da' },
    { 'mui-indigo-300': '#7986cb' },
    { 'mui-indigo-400': '#5c6bc0' },
    { 'mui-indigo-50': '#e8eaf6' },
    { 'mui-indigo-500': '#3f51b5' },
    { 'mui-indigo-600': '#3949ab' },
    { 'mui-indigo-700': '#303f9f' },
    { 'mui-indigo-800': '#283593' },
    { 'mui-indigo-900': '#1a237e' },
    { 'mui-indigo-a100': '#8c9eff' },
    { 'mui-indigo-a200': '#536dfe' },
    { 'mui-indigo-a400': '#3d5afe' },
    { 'mui-indigo-a700': '#304ffe' },
    { 'mui-light-blue-100': '#b3e5fc' },
    { 'mui-light-blue-200': '#81d4fa' },
    { 'mui-light-blue-300': '#4fc3f7' },
    { 'mui-light-blue-400': '#29b6f6' },
    { 'mui-light-blue-50': '#e1f5fe' },
    { 'mui-light-blue-500': '#03a9f4' },
    { 'mui-light-blue-600': '#039be5' },
    { 'mui-light-blue-700': '#0288d1' },
    { 'mui-light-blue-800': '#0277bd' },
    { 'mui-light-blue-900': '#01579b' },
    { 'mui-light-blue-a100': '#80d8ff' },
    { 'mui-light-blue-a200': '#40c4ff' },
    { 'mui-light-blue-a400': '#00b0ff' },
    { 'mui-light-blue-a700': '#0091ea' },
    { 'mui-light-green-100': '#dcedc8' },
    { 'mui-light-green-200': '#c5e1a5' },
    { 'mui-light-green-300': '#aed581' },
    { 'mui-light-green-400': '#9ccc65' },
    { 'mui-light-green-50': '#f1f8e9' },
    { 'mui-light-green-500': '#8bc34a' },
    { 'mui-light-green-600': '#7cb342' },
    { 'mui-light-green-700': '#689f38' },
    { 'mui-light-green-800': '#558b2f' },
    { 'mui-light-green-900': '#33691e' },
    { 'mui-light-green-a100': '#ccff90' },
    { 'mui-light-green-a200': '#b2ff59' },
    { 'mui-light-green-a400': '#76ff03' },
    { 'mui-light-green-a700': '#64dd17' },
    { 'mui-lime-100': '#f0f4c3' },
    { 'mui-lime-200': '#e6ee9c' },
    { 'mui-lime-300': '#dce775' },
    { 'mui-lime-400': '#d4e157' },
    { 'mui-lime-50': '#f9fbe7' },
    { 'mui-lime-500': '#cddc39' },
    { 'mui-lime-600': '#c0ca33' },
    { 'mui-lime-700': '#afb42b' },
    { 'mui-lime-800': '#9e9d24' },
    { 'mui-lime-900': '#827717' },
    { 'mui-lime-a100': '#f4ff81' },
    { 'mui-lime-a200': '#eeff41' },
    { 'mui-lime-a400': '#c6ff00' },
    { 'mui-lime-a700': '#aeea00' },
    { 'mui-orange-100': '#ffe0b2' },
    { 'mui-orange-200': '#ffcc80' },
    { 'mui-orange-300': '#ffb74d' },
    { 'mui-orange-400': '#ffa726' },
    { 'mui-orange-50': '#fff3e0' },
    { 'mui-orange-500': '#ff9800' },
    { 'mui-orange-600': '#fb8c00' },
    { 'mui-orange-700': '#f57c00' },
    { 'mui-orange-800': '#ef6c00' },
    { 'mui-orange-900': '#e65100' },
    { 'mui-orange-a100': '#ffd180' },
    { 'mui-orange-a200': '#ffab40' },
    { 'mui-orange-a400': '#ff9100' },
    { 'mui-orange-a700': '#ff6d00' },
    { 'mui-pink-100': '#f8bbd0' },
    { 'mui-pink-200': '#f48fb1' },
    { 'mui-pink-300': '#f06292' },
    { 'mui-pink-400': '#ec407a' },
    { 'mui-pink-50': '#fce4ec' },
    { 'mui-pink-500': '#e91e63' },
    { 'mui-pink-600': '#d81b60' },
    { 'mui-pink-700': '#c2185b' },
    { 'mui-pink-800': '#ad1457' },
    { 'mui-pink-900': '#880e4f' },
    { 'mui-pink-a100': '#ff80ab' },
    { 'mui-pink-a200': '#ff4081' },
    { 'mui-pink-a400': '#f50057' },
    { 'mui-pink-a700': '#c51162' },
    { 'mui-purple-100': '#e1bee7' },
    { 'mui-purple-200': '#ce93d8' },
    { 'mui-purple-300': '#ba68c8' },
    { 'mui-purple-400': '#ab47bc' },
    { 'mui-purple-50': '#f3e5f5' },
    { 'mui-purple-500': '#9c27b0' },
    { 'mui-purple-600': '#8e24aa' },
    { 'mui-purple-700': '#7b1fa2' },
    { 'mui-purple-800': '#6a1b9a' },
    { 'mui-purple-900': '#4a148c' },
    { 'mui-purple-a100': '#ea80fc' },
    { 'mui-purple-a200': '#e040fb' },
    { 'mui-purple-a400': '#d500f9' },
    { 'mui-purple-a700': '#aa00ff' },
    { 'mui-red-100': '#ffcdd2' },
    { 'mui-red-200': '#ef9a9a' },
    { 'mui-red-300': '#e57373' },
    { 'mui-red-400': '#ef5350' },
    { 'mui-red-50': '#ffebee' },
    { 'mui-red-500': '#f44336' },
    { 'mui-red-600': '#e53935' },
    { 'mui-red-700': '#d32f2f' },
    { 'mui-red-800': '#c62828' },
    { 'mui-red-900': '#b71c1c' },
    { 'mui-red-a100': '#ff8a80' },
    { 'mui-red-a200': '#ff5252' },
    { 'mui-red-a400': '#ff1744' },
    { 'mui-red-a700': '#d50000' },
    { 'mui-teal-100': '#b2dfdb' },
    { 'mui-teal-200': '#80cbc4' },
    { 'mui-teal-300': '#4db6ac' },
    { 'mui-teal-400': '#26a69a' },
    { 'mui-teal-50': '#e0f2f1' },
    { 'mui-teal-500': '#009688' },
    { 'mui-teal-600': '#00897b' },
    { 'mui-teal-700': '#00796b' },
    { 'mui-teal-800': '#00695c' },
    { 'mui-teal-900': '#004d40' },
    { 'mui-teal-a100': '#a7ffeb' },
    { 'mui-teal-a200': '#64ffda' },
    { 'mui-teal-a400': '#1de9b6' },
    { 'mui-teal-a700': '#00bfa5' },
    { 'mui-yellow-100': '#fff9c4' },
    { 'mui-yellow-200': '#fff59d' },
    { 'mui-yellow-300': '#fff176' },
    { 'mui-yellow-400': '#ffee58' },
    { 'mui-yellow-50': '#fffde7' },
    { 'mui-yellow-500': '#ffeb3b' },
    { 'mui-yellow-600': '#fdd835' },
    { 'mui-yellow-700': '#fbc02d' },
    { 'mui-yellow-800': '#f9a825' },
    { 'mui-yellow-900': '#f57f17' },
    { 'mui-yellow-a100': '#ffff8d' },
    { 'mui-yellow-a200': '#ffff00' },
    { 'mui-yellow-a400': '#ffea00' },
    { 'mui-yellow-a700': '#ffd600' },
];

/* or radiuses */
export const borderRadii = [
    '100%',
    '10px',
    '1px',
    '2px',
    '3px',
    '5px',
];

export const borderWidths = [
    '1px',
    '2px',
    '3px',
    '5px',
    'medium',
    'thick',
    'thin',
];

export const borderStyles = [
    'dashed',
    'dotted',
    'double',
    'groove',
    'hidden',
    'inset',
    'none',
    'outset',
    'ridge',
    'solid',
];

export const positionDistances = [
    'auto',
    '-75%',
    '-66%',
    '-50%',
    '-33%',
    '-25%',
    '25%',
    '33%',
    '50%',
    '66%',
    '75%',
    '100%',
    '0',
    '1rem',
    '1px',
    '-1px',
];

export const gridTracks = [
    'none',
    'auto',
    'subgrid',
    'masonry',
    '1fr',
    'repeat(2, 1fr)',
    'repeat(3, 1fr)',
    'repeat(4, 1fr)',
    'repeat(5, 1fr)',
    'repeat(6, 1fr)',
    'repeat(7, 1fr)',
    'repeat(8, 1fr)',
    'repeat(9, 1fr)',
    'repeat(10, 1fr)',
    'repeat(11, 1fr)',
    'repeat(12, 1fr)',
    'repeat(13, 1fr)',
    'repeat(14, 1fr)',
    'repeat(15, 1fr)',
    'repeat(16, 1fr)',
    'repeat(17, 1fr)',
    'repeat(18, 1fr)',
    'repeat(19, 1fr)',
    'repeat(20, 1fr)',
    'repeat(21, 1fr)',
    'repeat(22, 1fr)',
    'repeat(23, 1fr)',
    'repeat(24, 1fr)',
];

export const gapDistances = [
    '.25rem',
    '.5rem',
    '.75rem',
    '.875rem',
    '1rem',
    '1.25rem',
    '1.5rem',
    '1.75rem',
    '1.875rem',
    '2rem',
    'normal',
];

export const widthsAndHeights = [
    '0%',
    '10%',
    '20%',
    '25%',
    '30%',
    '33%',
    '40%',
    '50%',
    '60%',
    '66%',
    '70%',
    '75%',
    '80%',
    '90%',
    '100%',
    'auto',
];

export const filters = [
    'blur(0%)',
    'blur(100%)',
    'blur(10%)',
    'blur(20%)',
    'blur(30%)',
    'blur(40%)',
    'blur(50%)',
    'blur(60%)',
    'blur(70%)',
    'blur(80%)',
    'blur(90%)',
    'brightness(0%)',
    'brightness(100%)',
    'brightness(10%)',
    'brightness(20%)',
    'brightness(30%)',
    'brightness(40%)',
    'brightness(50%)',
    'brightness(60%)',
    'brightness(70%)',
    'brightness(80%)',
    'brightness(90%)',
    'contrast(0%)',
    'contrast(100%)',
    'contrast(10%)',
    'contrast(20%)',
    'contrast(30%)',
    'contrast(40%)',
    'contrast(50%)',
    'contrast(60%)',
    'contrast(70%)',
    'contrast(80%)',
    'contrast(90%)',
    'grayscale(0%)',
    'grayscale(100%)',
    'grayscale(10%)',
    'grayscale(20%)',
    'grayscale(30%)',
    'grayscale(40%)',
    'grayscale(50%)',
    'grayscale(60%)',
    'grayscale(70%)',
    'grayscale(80%)',
    'grayscale(90%)',
    'hue-rotate(0deg)',
    'hue-rotate(100deg)',
    'hue-rotate(105deg)',
    'hue-rotate(10deg)',
    'hue-rotate(110deg)',
    'hue-rotate(115deg)',
    'hue-rotate(120deg)',
    'hue-rotate(125deg)',
    'hue-rotate(130deg)',
    'hue-rotate(135deg)',
    'hue-rotate(140deg)',
    'hue-rotate(145deg)',
    'hue-rotate(150deg)',
    'hue-rotate(155deg)',
    'hue-rotate(15deg)',
    'hue-rotate(160deg)',
    'hue-rotate(165deg)',
    'hue-rotate(170deg)',
    'hue-rotate(175deg)',
    'hue-rotate(180deg)',
    'hue-rotate(185deg)',
    'hue-rotate(190deg)',
    'hue-rotate(195deg)',
    'hue-rotate(200deg)',
    'hue-rotate(205deg)',
    'hue-rotate(20deg)',
    'hue-rotate(210deg)',
    'hue-rotate(215deg)',
    'hue-rotate(220deg)',
    'hue-rotate(225deg)',
    'hue-rotate(230deg)',
    'hue-rotate(235deg)',
    'hue-rotate(240deg)',
    'hue-rotate(245deg)',
    'hue-rotate(250deg)',
    'hue-rotate(255deg)',
    'hue-rotate(25deg)',
    'hue-rotate(260deg)',
    'hue-rotate(265deg)',
    'hue-rotate(270deg)',
    'hue-rotate(275deg)',
    'hue-rotate(280deg)',
    'hue-rotate(285deg)',
    'hue-rotate(290deg)',
    'hue-rotate(295deg)',
    'hue-rotate(300deg)',
    'hue-rotate(305deg)',
    'hue-rotate(30deg)',
    'hue-rotate(310deg)',
    'hue-rotate(315deg)',
    'hue-rotate(320deg)',
    'hue-rotate(325deg)',
    'hue-rotate(330deg)',
    'hue-rotate(335deg)',
    'hue-rotate(340deg)',
    'hue-rotate(345deg)',
    'hue-rotate(350deg)',
    'hue-rotate(355deg)',
    'hue-rotate(35deg)',
    'hue-rotate(360deg)',
    'hue-rotate(40deg)',
    'hue-rotate(45deg)',
    'hue-rotate(50deg)',
    'hue-rotate(55deg)',
    'hue-rotate(5deg)',
    'hue-rotate(60deg)',
    'hue-rotate(65deg)',
    'hue-rotate(70deg)',
    'hue-rotate(75deg)',
    'hue-rotate(80deg)',
    'hue-rotate(85deg)',
    'hue-rotate(90deg)',
    'hue-rotate(95deg)',
    'invert(0%)',
    'invert(100%)',
    'invert(10%)',
    'invert(20%)',
    'invert(30%)',
    'invert(40%)',
    'invert(50%)',
    'invert(60%)',
    'invert(70%)',
    'invert(80%)',
    'invert(90%)',
    'opacity(0%)',
    'opacity(100%)',
    'opacity(10%)',
    'opacity(20%)',
    'opacity(30%)',
    'opacity(40%)',
    'opacity(50%)',
    'opacity(60%)',
    'opacity(70%)',
    'opacity(80%)',
    'opacity(90%)',
    'saturate(0%)',
    'saturate(100%)',
    'saturate(10%)',
    'saturate(20%)',
    'saturate(30%)',
    'saturate(40%)',
    'saturate(50%)',
    'saturate(60%)',
    'saturate(70%)',
    'saturate(80%)',
    'saturate(90%)',
    'sepia(0%)',
    'sepia(100%)',
    'sepia(10%)',
    'sepia(20%)',
    'sepia(30%)',
    'sepia(40%)',
    'sepia(50%)',
    'sepia(60%)',
    'sepia(70%)',
    'sepia(80%)',
    'sepia(90%)',
];

export const fontSizes = [
    '8px',
    '9px',
    '10px',
    '12px',
    '14px',
    '16px',
    '18px',
    '20px',
    '22px',
    '24px',
    '26px',
    '28px',
    '30px',
    '32px',
    '34px',
    '36px',
    '38px',
    '40px',
    '42px',
    '.75rem',
    '.875rem',
    '1rem',
    '1.25rem',
    '1.5rem',
    '1.75rem',
    '1.875rem',
    '2rem',
    '2.25rem',
    '2.5rem',
    '2.75rem',
    '2.875rem',
    '3rem',
    '4rem',
    '5rem',
    'xx-small',
    'x-small',
    'small',
    'medium',
    'large',
    'x-large',
    'xx-large',
    'xxx-large',
    'smaller',
    'larger',
];

export const boxShadows = [
    '0px 0px 5px rgba(0,0,0,.9)',
    '0px 0px 5px rgba(0,0,0,.8)',
    '0px 0px 5px rgba(0,0,0,.7)',
    '0px 0px 5px rgba(0,0,0,.6)',
    '0px 0px 5px rgba(0,0,0,.5)',
    '0px 0px 5px rgba(0,0,0,.4)',
    '0px 0px 5px rgba(0,0,0,.3)',
    '0px 0px 5px rgba(0,0,0,.2)',
    '0px 0px 5px rgba(0,0,0,.1)',
];

export const textShadows = [
    '1px 1px 1px rgba(255,255,255,.9)',
    '1px 1px 1px rgba(255,255,255,.8)',
    '1px 1px 1px rgba(255,255,255,.7)',
    '1px 1px 1px rgba(255,255,255,.6)',
    '1px 1px 1px rgba(255,255,255,.5)',
    '1px 1px 1px rgba(255,255,255,.4)',
    '1px 1px 1px rgba(255,255,255,.3)',
    '1px 1px 1px rgba(255,255,255,.2)',
    '1px 1px 1px rgba(255,255,255,.1)',
];

export const fontStacks = [
    {
        'transitional-font-stack':
            "'Charter, 'Bitstream Charter', 'Sitka Text', Cambria, serif'",
    },
    {
        'old-style-font-stack':
            "'Iowan Old Style', 'Palatino Linotype', 'URW Palladio L', P052, serif'",
    },
    {
        'humanist-font-stack':
            "'Seravek, 'Gill Sans Nova', Ubuntu, Calibri, 'DejaVu Sans', source-sans-pro, sans-serif'",
    },
    {
        'geometric-humanist-font-stack':
            "'Avenir, Montserrat, Corbel, 'URW Gothic', source-sans-pro, sans-serif'",
    },
    {
        'classical-humanist-font-stack':
            "'Optima, Candara, 'Noto Sans', source-sans-pro, sans-serif'",
    },
    {
        'neo-grotesque-font-stack':
            "'Inter, Roboto, 'Helvetica Neue', 'Arial Nova', 'Nimbus Sans', Arial, sans-serif'",
    },
    {
        'monospace-slab-serif-font-stack':
            "'Nimbus Mono PS', 'Courier New', monospace'",
    },
    {
        'monospace-code-font-stack':
            "'ui-monospace, 'Cascadia Code', 'Source Code Pro', Menlo, Consolas, 'DejaVu Sans Mono', monospace'",
    },
    {
        'industrial-font-stack':
            "'Bahnschrift, 'DIN Alternate', 'Franklin Gothic Medium', 'Nimbus Sans Narrow', sans-serif-condensed, sans-serif'",
    },
    {
        'rounded-sans-font-stack':
            "'ui-rounded, 'Hiragino Maru Gothic ProN', Quicksand, Comfortaa, Manjari, 'Arial Rounded MT', 'Arial Rounded MT Bold', Calibri, source-sans-pro, sans-serif'",
    },
    {
        'slab-serif-font-stack':
            "'Rockwell, 'Rockwell Nova', 'Roboto Slab', 'DejaVu Serif', 'Sitka Small', serif'",
    },
    {
        'antique-font-stack':
            "Superclarendon, 'Bookman Old Style', 'URW Bookman', 'URW Bookman L', 'Georgia Pro', Georgia, serif'",
    },
    {
        'didone-font-stack':
            "Didot, 'Bodoni MT', 'Noto Serif Display', 'URW Palladio L', P052, Sylfaen, serif'",
    },
    {
        'handwritten-font-stack':
            "'Segoe Print', 'Bradley Hand', Chilanka, TSCu_Comic, casual, cursive'",
    },
];

export const googleFonts = [
    'Abhaya Libre',
    'Aboreto',
    'Abril Fatface',
    'Abyssinica SIL',
    'Aclonica',
    'Acme',
    'Actor',
    'Adamina',
    'Advent Pro',
    'Agdasima',
    'Aguafina Script',
    'Akatab',
    'Akaya Kanadaka',
    'Akaya Telivigala',
    'Akronim',
    'Akshar',
    'Aladin',
    'Alata',
    'Alatsi',
    'Albert Sans',
    'Aldrich',
    'Alef',
    'Alegreya',
    'Alegreya Sans',
    'Alegreya Sans SC',
    'Alegreya SC',
    'Aleo',
    'Alex Brush',
    'Alexandria',
    'Alfa Slab One',
    'Alice',
    'Alike',
    'Alike Angular',
    'Alkalami',
    'Alkatra',
    'Allan',
    'Allerta',
    'Allerta Stencil',
    'Allison',
    'Allura',
    'Almarai',
    'Almendra',
    'Almendra',
    'Almendra SC',
    'Alumni Sans',
    'Alumni Sans Collegiate One ',
    'Alumni Sans Inline One',
    'Alumni Sans Pinstripe',
    'Amarante',
    'Amaranth',
    'Amatic SC',
    'Amethysta',
    'Amiko',
    'Amiri',
    'Amiri Quran',
    'Amita',
    'Anaheim',
    'Andada Pro',
    'Andika',
    'Anek Bangla',
    'Anek Devanagari',
    'Anek Gujarati',
    'Anek Gurmukhi',
    'Anek Kannada',
    'Anek Latin',
    'Anek Malayalam',
    'Anek Odia',
    'Anek Tamil',
    'Anek Telugu',
    'Angkor',
    'Annie Use Your Telescope',
    'Anonymous Pro',
    'Antic',
    'Antic Didone',
    'Antic Slab',
    'Anton',
    'Antonio',
    'Anuphan',
    'Anybody',
    'Aoboshi One',
    'Arapey',
    'Arbutus',
    'Arbutus Slab',
    'Architects Daughter',
    'Archivo',
    'Archivo Black',
    'Archivo Narrow',
    'Are You Serious',
    'Aref Ruqaa',
    'Aref Ruqaa Ink',
    'Arima',
    'Arimo',
    'Arizonia',
    'Armata',
    'Arsenal',
    'Artifika',
    'Arvo',
    'Arya',
    'Asap',
    'Asap Condensed',
    'Asar',
    'Asset',
    'Assistant',
    'Astloch',
    'Asul',
    'Athiti',
    'Atkinson Hyperlegible',
    'Atma',
    'Atomic Age',
    'Aubrey',
    'Audiowide',
    'Autour One',
    'Average',
    'Average Sans',
    'Averia Gruesa Libre',
    'Averia Libre',
    'Averia Sans Libre',
    'Averia  Libre',
    'Azeret Mono',
    'B612',
    'B612 Mono',
    'Babylonica',
    'Bacasime Antique',
    'Bad Script',
    'Bagel Fat One',
    'Bahiana',
    'Bahianita',
    'Bai Jamjuree',
    'Bakbak One',
    'Ballet',
    'Baloo 2',
    'Baloo Bhai 2',
    'Baloo Bhaijaan 2',
    'Baloo Bhaina 2',
    'Baloo Chettan 2',
    'Baloo Da 2',
    'Baloo Paaji 2',
    'Baloo Tamma 2',
    'Baloo Tammudu 2',
    'Baloo Thambi 2',
    'Balsamiq Sans',
    'Balthazar',
    'Bangers',
    'Barlow',
    'Barlow Condensed',
    'Barlow Semi Condensed',
    'Barriecito',
    'Barrio',
    'Basic',
    'Baskervville',
    'Battambang',
    'Baumans',
    'Bayon',
    'Be Vietnam Pro',
    'Beau Rivage',
    'Bebas Neue',
    'Belanosima',
    'Belgrano',
    'Bellefair',
    'Belleza',
    'Bellota',
    'Bellota Text',
    'BenchNine',
    'Benne',
    'Bentham',
    'Berkshire Swash',
    'Besley',
    'Beth Ellen',
    'Bevan',
    'BhuTuka Expanded One',
    'Big Shoulders ',
    'Big Shoulders Inline ',
    'Big Shoulders Inline Text ',
    'Big Shoulders Stencil ',
    'Big Shoulders Stencil Text ',
    'Big Shoulders Text',
    'Bigelow Rules',
    'Bigshot One',
    'Bilbo',
    'Bilbo Swash Caps',
    'BioRhyme',
    'BioRhyme Expanded',
    'Birthstone',
    'Birthstone Bounce',
    'Biryani',
    'Bitter',
    'BIZ UDGothic',
    'BIZ UDMincho',
    'BIZ UDPGothic',
    'BIZ UDPMincho',
    'Black And White Picture',
    'Black Han Sans',
    'Black Ops One',
    'Blaka',
    'Blaka Hollow',
    'Blaka Ink',
    'Blinker',
    'Bodoni Moda',
    'Bokor',
    'Bona Nova',
    'Bonbon',
    'Bonheur Royale',
    'Boogaloo',
    'Bowlby One',
    'Bowlby One SC',
    'Braah One',
    'Brawler',
    'Bree ',
    'Bruno Ace',
    'Bruno Ace SC',
    'Brygada 1918',
    'Bubblegum Sans',
    'Bubbler One',
    'Buda',
    'Buenard',
    'Bungee',
    'Bungee Hairline',
    'Bungee Inline',
    'Bungee Outline',
    'Bungee Shade',
    'Bungee Spice',
    'Butcherman',
    'Butterfly Kids',
    'Cabin',
    'Cabin Condensed',
    'Cabin Sketch',
    'Caesar Dressing',
    'Cagliostro',
    'Cairo',
    'Cairo Play',
    'Caladea',
    'Calistoga',
    'Calligraffitti',
    'Cambay',
    'Cambo',
    'Candal',
    'Cantarell',
    'Cantata One',
    'Cantora One',
    'Caprasimo',
    'Capriola',
    'Caramel',
    'Carattere',
    'Cardo',
    'Carlito',
    'Carme',
    'Carrois Gothic',
    'Carrois Gothic SC',
    'Carter One',
    'Castoro',
    'Castoro Titling',
    'Catamaran',
    'Caudex',
    'Caveat',
    'Caveat Brush',
    'Cedarville Cursive',
    'Ceviche One',
    'Chakra Petch',
    'Changa',
    'Changa One',
    'Chango',
    'Charis SIL',
    'Charm',
    'Charmonman',
    'Chathura',
    'Chau Philomene One',
    'Chela One',
    'Chelsea Market',
    'Chenla',
    'Cherish',
    'Cherry Bomb One',
    'Cherry Cream Soda',
    'Cherry Swash',
    'Chewy',
    'Chicle',
    'Chilanka',
    'Chivo',
    'Chivo Mono',
    'Chokokutai',
    'Chonburi',
    'Cinzel',
    'Cinzel Decorative',
    'Clicker Script',
    'Climate Crisis',
    'Coda',
    'Codystar',
    'Coiny',
    'Combo',
    'Comfortaa',
    'Comforter',
    'Comforter Brush',
    'Comic Neue',
    'Coming Soon',
    'Comme',
    'Commissioner',
    'Concert One',
    'Condiment',
    'Content',
    'Contrail One',
    'Convergence',
    'Cookie',
    'Copse',
    'Corben',
    'Corinthia',
    'Cormorant',
    'Cormorant Garamond',
    'Cormorant Infant',
    'Cormorant SC',
    'Cormorant Unicase',
    'Cormorant Upright',
    'Courgette',
    'Courier Prime',
    'Cousine',
    'Coustard',
    'Covered By Your Grace',
    'Crafty Girls',
    'Creepster',
    'Crete Round',
    'Crimson Pro',
    'Crimson Text',
    'Croissant One',
    'Crushed',
    'Cuprum',
    'Cute Font',
    'Cutive',
    'Cutive Mono',
    'Damion',
    'Dancing Script',
    'Dangrek',
    'Darker Grotesque',
    'Darumadrop One',
    'David Libre',
    'Dawning of a New Day',
    'Days One',
    'Dekko',
    'Dela Gothic One',
    'Delicious Handrawn',
    'Delius',
    'Delius Swash Caps',
    'Delius Unicase',
    'Della Respira',
    'Denk One',
    'Devonshire',
    'Dhurjati',
    'Didact Gothic',
    'Diphylleia',
    'Diplomata',
    'Diplomata SC',
    'DM Mono',
    'DM Sans',
    'DM  ',
    'DM  Text',
    'Do Hyeon',
    'Dokdo',
    'Domine',
    'Donegal One',
    'Dongle',
    'Doppio One',
    'Dorsa',
    'Dosis',
    'DotGothic16',
    'Dr Sugiyama',
    'Duru Sans',
    'Dynalight',
    'DynaPuff',
    'Eagle Lake',
    'East Sea Dokdo',
    'Eater',
    'EB Garamond',
    'Economica',
    'Eczar',
    'Edu NSW ACT Foundation',
    'Edu QLD Beginner',
    'Edu SA Beginner',
    'Edu TAS Beginner',
    'Edu VIC WA NT Beginner',
    'El Messiri',
    'Electrolize',
    'Elsie',
    'Elsie Swash Caps',
    'Emblema One',
    'Emilys Candy',
    'Encode Sans',
    'Encode Sans Condensed',
    'Encode Sans Expanded',
    'Encode Sans SC',
    'Encode Sans Semi Condensed',
    'Encode Sans Semi Expanded',
    'Engagement',
    'Englebert',
    'Enriqueta',
    'Ephesis',
    'Epilogue',
    'Erica One',
    'Esteban',
    'Estonia',
    'Euphoria Script',
    'Ewert',
    'Exo',
    'Exo 2',
    'Expletus Sans',
    'Explora',
    'Fahkwang',
    'Familjen Grotesk',
    'Fanwood Text',
    'Farro',
    'Farsan',
    'Fascinate',
    'Fascinate Inline',
    'Faster One',
    'Fasthand',
    'Fauna One',
    'Faustina',
    'Federant',
    'Federo',
    'Felipa',
    'Fenix',
    'Festive',
    'Figtree',
    'Finger Paint',
    'Finlandica',
    'Fira Code',
    'Fira Mono',
    'Fira Sans',
    'Fira Sans Condensed',
    'Fira Sans Extra Condensed',
    'Fjalla One',
    'Fjord One',
    'Flamenco',
    'Flavors',
    'Fleur De Leah',
    'Flow Block',
    'Flow Circular',
    'Flow Rounded',
    'Foldit',
    'Fondamento',
    'Fontdiner Swanky',
    'Forum',
    'Fragment Mono',
    'Francois One',
    'Frank Ruhl Libre',
    'Fraunces',
    'Freckle Face',
    'Fredericka the Great',
    'Fredoka',
    'Freehand',
    'Fresca',
    'Frijole',
    'Fruktur',
    'Fugaz One',
    'Fuggles',
    'Fuzzy Bubbles',
    'Gabriela',
    'Gaegu',
    'Gafata',
    'Gajraj One',
    'Galada',
    'Galdeano',
    'Galindo',
    'Gamja Flower',
    'Gantari',
    'Gasoek One',
    'Gayathri',
    'Gelasio',
    'Gemunu Libre',
    'Genos',
    'Gentium Book Plus',
    'Gentium Plus',
    'Geo',
    'Geologica',
    'Georama',
    'Geostar',
    'Geostar Fill',
    'Germania One',
    'GFS Didot',
    'GFS Neohellenic',
    'Gideon Roman',
    'Gidugu',
    'Gilda ',
    'Girassol',
    'Give You Glory',
    'Glass Antiqua',
    'Glegoo',
    'Gloock',
    'Gloria Hallelujah',
    'Glory',
    'Gluten',
    'Goblin One',
    'Gochi Hand',
    'Goldman',
    'Golos Text',
    'Gorditas',
    'Gothic A1',
    'Gotu',
    'Goudy Bookletter 1911',
    'Gowun Batang',
    'Gowun Dodum',
    'Graduate',
    'Grand Hotel',
    'Grandiflora One',
    'Grandstander',
    'Grape Nuts',
    'Gravitas One',
    'Great Vibes',
    'Grechen Fuemen',
    'Grenze',
    'Grenze Gotisch',
    'Grey Qo',
    'Griffy',
    'Gruppo',
    'Gudea',
    'Gugi',
    'Gulzar',
    'Gupter',
    'Gurajada',
    'Gwendolyn',
    'Habibi',
    'Hachi Maru Pop',
    'Hahmlet',
    'Halant',
    'Hammersmith One',
    'Hanalei',
    'Hanalei Fill',
    'Handlee',
    'Hanken Grotesk',
    'Hanuman',
    'Happy Monkey',
    'Harmattan',
    'Headland One',
    'Heebo',
    'Henny Penny',
    'Hepta Slab',
    'Herr Von Muellerhoff',
    'Hi Melody',
    'Hina Mincho',
    'Hind',
    'Hind Guntur',
    'Hind Madurai',
    'Hind Siliguri',
    'Hind Vadodara',
    'Holtwood One SC',
    'Homemade Apple',
    'Homenaje',
    'Hubballi',
    'Hurricane',
    'Ibarra Real Nova',
    'IBM Plex Mono',
    'IBM Plex Sans',
    'IBM Plex Sans Arabic',
    'IBM Plex Sans Condensed',
    'IBM Plex Sans Devanagari',
    'IBM Plex Sans Hebrew',
    'IBM Plex Sans JP',
    'IBM Plex Sans KR',
    'IBM Plex Sans Thai',
    'IBM Plex Sans Thai Looped ',
    'IBM Plex ',
    'Iceberg',
    'Iceland',
    'IM Fell Double Pica',
    'IM Fell Double Pica SC',
    'IM Fell DW Pica',
    'IM Fell DW Pica SC',
    'IM Fell English',
    'IM Fell English SC',
    'IM Fell French Canon',
    'IM Fell French Canon SC',
    'IM Fell Great Primer',
    'IM Fell Great Primer SC',
    'Imbue',
    'Imperial Script',
    'Imprima',
    'Inconsolata',
    'Inder',
    'Indie Flower',
    'Ingrid Darling',
    'Inika',
    'Inknut Antiqua',
    'Inria Sans',
    'Inria ',
    'Inspiration',
    'Instrument Sans',
    'Instrument ',
    'Inter',
    'Inter Tight',
    'Irish Grover',
    'Island Moments',
    'Istok Web',
    'Italiana',
    'Italianno',
    'Itim',
    'Jacques Francois',
    'Jacques Francois Shadow',
    'Jaldi',
    'JetBrains Mono',
    'Jim Nightshade',
    'Joan',
    'Jockey One',
    'Jolly Lodger',
    'Jomhuria',
    'Jomolhari',
    'Josefin Sans',
    'Josefin Slab',
    'Jost',
    'Joti One',
    'Jua',
    'Judson',
    'Julee',
    'Julius Sans One',
    'Junge',
    'Jura',
    'Just Another Hand',
    'Just Me Again Down Here',
    'K2D',
    'Kablammo',
    'Kadwa',
    'Kaisei Decol',
    'Kaisei HarunoUmi',
    'Kaisei Opti',
    'Kaisei Tokumin',
    'Kalam',
    'Kameron',
    'Kanit',
    'Kantumruy Pro',
    'Karantina',
    'Karla',
    'Karma',
    'Katibeh',
    'Kaushan Script',
    'Kavivanar',
    'Kavoon',
    'Kdam Thmor Pro',
    'Keania One',
    'Kelly Slab',
    'Kenia',
    'Khand',
    'Khmer',
    'Khula',
    'Kings',
    'Kirang Haerang',
    'Kite One',
    'Kiwi Maru',
    'Klee One',
    'Knewave',
    'Kodchasan',
    'Koh Santepheap',
    'KoHo',
    'Kolker Brush',
    'Konkhmer Sleokchher',
    'Kosugi',
    'Kosugi Maru',
    'Kotta One',
    'Koulen',
    'Kranky',
    'Kreon',
    'Kristi',
    'Krona One',
    'Krub',
    'Kufam',
    'Kulim Park',
    'Kumar One',
    'Kumar One Outline',
    'Kumbh Sans',
    'Kurale',
    'La Belle Aurore',
    'Labrada',
    'Lacquer',
    'Laila',
    'Lakki Reddy',
    'Lalezar',
    'Lancelot',
    'Langar',
    'Lateef',
    'Lato',
    'Lavishly Yours',
    'League Gothic',
    'League Script',
    'League Spartan',
    'Leckerli One',
    'Ledger',
    'Lekton',
    'Lemon',
    'Lemonada',
    'Lexend',
    'Lexend Deca',
    'Lexend Exa',
    'Lexend Giga',
    'Lexend Mega',
    'Lexend Peta',
    'Lexend Tera',
    'Lexend Zetta',
    'Libre Barcode 128',
    'Libre Barcode 128 Text',
    'Libre Barcode 39',
    'Libre Barcode 39 Extended ',
    'Libre Barcode 39 Extended Text ',
    'Libre Barcode 39 Text',
    'Libre Barcode EAN13 Text',
    'Libre Baskerville',
    'Libre Bodoni',
    'Libre Caslon ',
    'Libre Caslon Text',
    'Libre Franklin',
    'Licorice',
    'Life Savers',
    'Lilita One',
    'Lily Script One',
    'Limelight',
    'Linden Hill',
    'Literata',
    'Liu Jian Mao Cao',
    'Livvic',
    'Lobster',
    'Lobster Two',
    'Londrina Outline',
    'Londrina Shadow',
    'Londrina Sketch',
    'Londrina Solid',
    'Long Cang',
    'Lora',
    'Love Light',
    'Love Ya Like A Sister',
    'Loved by the King',
    'Lovers Quarrel',
    'Luckiest Guy',
    'Lugrasimo',
    'Lumanosimo',
    'Lunasima',
    'Lusitana',
    'Lustria',
    'Luxurious Roman',
    'Luxurious Script',
    'M PLUS 1',
    'M PLUS 1 Code',
    'M PLUS 1p',
    'M PLUS 2',
    'M PLUS Code Latin',
    'M PLUS Rounded 1c',
    'Ma Shan Zheng',
    'Macondo',
    'Macondo Swash Caps',
    'Mada',
    'Magra',
    'Maiden Orange',
    'Maitree',
    'Major Mono ',
    'Mako',
    'Mali',
    'Mallanna',
    'Mandali',
    'Manjari',
    'Manrope',
    'Mansalva',
    'Manuale',
    'Marcellus',
    'Marcellus SC',
    'Marck Script',
    'Margarine',
    'Marhey',
    'Markazi Text',
    'Marko One',
    'Marmelad',
    'Martel',
    'Martel Sans',
    'Martian Mono',
    'Marvel',
    'Mate',
    'Mate SC',
    'Material Icons',
    'Material Icons Outlined',
    'Material Icons Round',
    'Material Icons Sharp',
    'Material Icons Two Tone',
    'Material Symbols Outlined ',
    'Material Symbols Rounded',
    'Material Symbols Sharp',
    'Maven Pro',
    'McLaren',
    'Mea Culpa',
    'Meddon',
    'MedievalSharp',
    'Medula One',
    'Meera Inimai',
    'Megrim',
    'Meie Script',
    'Meow Script',
    'Merienda',
    'Merriweather',
    'Merriweather Sans',
    'Metal',
    'Metal Mania',
    'Metamorphous',
    'Metrophobic',
    'Michroma',
    'Milonga',
    'Miltonian',
    'Miltonian Tattoo',
    'Mina',
    'Mingzat',
    'Miniver',
    'Miriam Libre',
    'Mirza',
    'Miss Fajardose',
    'Mitr',
    'Mochiy Pop One',
    'Mochiy Pop P One',
    'Modak',
    'Modern Antiqua',
    'Mogra',
    'Mohave',
    'Moirai One',
    'Molengo',
    'Molle',
    'Monda',
    'Monofett',
    'Monomaniac One',
    'Monoton',
    'Monsieur La Doulaise',
    'Montaga',
    'Montagu Slab',
    'MonteCarlo',
    'Montez',
    'Montserrat',
    'Montserrat Alternates',
    'Montserrat Subrayada',
    'Moo Lah Lah',
    'Moon Dance',
    'Moul',
    'Moulpali',
    'Mountains of Christmas',
    'Mouse Memoirs',
    'Mr Bedfort',
    'Mr Dafoe',
    'Mr De Haviland',
    'Mrs Saint Delafield',
    'Mrs Sheppards',
    'Ms Madi',
    'Mukta',
    'Mukta Mahee',
    'Mukta Malar',
    'Mukta Vaani',
    'Mulish',
    'Murecho',
    'MuseoModerno',
    'My Soul',
    'Mynerve',
    'Mystery Quest',
    'Nabla',
    'Nanum Brush Script',
    'Nanum Gothic',
    'Nanum Gothic Coding',
    'Nanum Myeongjo',
    'Nanum Pen Script',
    'Narnoor',
    'Neonderthaw',
    'Nerko One',
    'Neucha',
    'Neuton',
    'New Rocker',
    'New Tegomin',
    'News Cycle',
    'Newsreader',
    'Niconne',
    'Niramit',
    'Nixie One',
    'Nobile',
    'Nokora',
    'Norican',
    'Nosifer',
    'Notable',
    'Nothing You Could Do',
    'Noticia Text',
    'Noto Color Emoji',
    'Noto Emoji',
    'Noto Kufi Arabic',
    'Noto Music',
    'Noto Naskh Arabic',
    'Noto Nastaliq Urdu',
    'Noto Rashi Hebrew',
    'Noto Sans',
    'Noto Sans Adlam',
    'Noto Sans Adlam Unjoined',
    'Noto Sans Anatolian Hieroglyphs ',
    'Noto Sans Arabic',
    'Noto Sans Armenian',
    'Noto Sans Avestan',
    'Noto Sans Balinese',
    'Noto Sans Bamum',
    'Noto Sans Bassa Vah',
    'Noto Sans Batak',
    'Noto Sans Bengali',
    'Noto Sans Bhaiksuki',
    'Noto Sans Brahmi',
    'Noto Sans Buginese',
    'Noto Sans Buhid',
    'Noto Sans Canadian Aboriginal ',
    'Noto Sans Carian',
    'Noto Sans Caucasian Albanian ',
    'Noto Sans Chakma',
    'Noto Sans Cham',
    'Noto Sans Cherokee',
    'Noto Sans Chorasmian',
    'Noto Sans Coptic',
    'Noto Sans Cuneiform',
    'Noto Sans Cypriot',
    'Noto Sans Cypro Minoan',
    'Noto Sans Deseret',
    'Noto Sans Devanagari',
    'Noto Sans ',
    'Noto Sans Duployan',
    'Noto Sans Egyptian Hieroglyphs ',
    'Noto Sans Elbasan',
    'Noto Sans Elymaic',
    'Noto Sans Ethiopic',
    'Noto Sans Georgian',
    'Noto Sans Glagolitic',
    'Noto Sans Gothic',
    'Noto Sans Grantha',
    'Noto Sans Gujarati',
    'Noto Sans Gunjala Gondi',
    'Noto Sans Gurmukhi',
    'Noto Sans Hanifi Rohingya ',
    'Noto Sans Hanunoo',
    'Noto Sans Hatran',
    'Noto Sans Hebrew',
    'Noto Sans HK',
    'Noto Sans Imperial Aramaic ',
    'Noto Sans Indic Siyaq Numbers ',
    'Noto Sans Inscriptional Pahlavi ',
    'Noto Sans Inscriptional Parthian ',
    'Noto Sans Javanese',
    'Noto Sans JP',
    'Noto Sans Kaithi',
    'Noto Sans Kannada',
    'Noto Sans Kayah Li',
    'Noto Sans Kharoshthi',
    'Noto Sans Khmer',
    'Noto Sans Khojki',
    'Noto Sans Khudawadi',
    'Noto Sans KR',
    'Noto Sans Lao',
    'Noto Sans Lao Looped',
    'Noto Sans Lepcha',
    'Noto Sans Limbu',
    'Noto Sans Linear A',
    'Noto Sans Linear B',
    'Noto Sans Lisu',
    'Noto Sans Lycian',
    'Noto Sans Lydian',
    'Noto Sans Mahajani',
    'Noto Sans Malayalam',
    'Noto Sans Mandaic',
    'Noto Sans Manichaean',
    'Noto Sans Marchen',
    'Noto Sans Masaram Gondi',
    'Noto Sans Math',
    'Noto Sans Mayan Numerals',
    'Noto Sans Medefaidrin',
    'Noto Sans Meetei Mayek',
    'Noto Sans Mende Kikakui',
    'Noto Sans Meroitic',
    'Noto Sans Miao',
    'Noto Sans Modi',
    'Noto Sans Mongolian',
    'Noto Sans Mono',
    'Noto Sans Mro',
    'Noto Sans Multani',
    'Noto Sans Myanmar',
    'Noto Sans Nabataean',
    'Noto Sans Nag Mundari',
    'Noto Sans Nandinagari',
    'Noto Sans New Tai Lue',
    'Noto Sans Newa',
    'Noto Sans NKo',
    'Noto Sans Nushu',
    'Noto Sans Ogham',
    'Noto Sans Ol Chiki',
    'Noto Sans Old Hungarian',
    'Noto Sans Old Italic',
    'Noto Sans Old North Arabian ',
    'Noto Sans Old Permic',
    'Noto Sans Old Persian',
    'Noto Sans Old Sogdian',
    'Noto Sans Old Turkic',
    'Noto Sans Oriya',
    'Noto Sans Osage',
    'Noto Sans Osmanya',
    'Noto Sans Pahawh Hmong',
    'Noto Sans Palmyrene',
    'Noto Sans Pau Cin Hau',
    'Noto Sans Phags Pa',
    'Noto Sans Phoenician',
    'Noto Sans Psalter Pahlavi ',
    'Noto Sans Rejang',
    'Noto Sans Runic',
    'Noto Sans Samaritan',
    'Noto Sans Saurashtra',
    'Noto Sans SC',
    'Noto Sans Sharada',
    'Noto Sans Shavian',
    'Noto Sans Siddham',
    'Noto Sans SignWriting',
    'Noto Sans Sinhala',
    'Noto Sans Sogdian',
    'Noto Sans Sora Sompeng',
    'Noto Sans Soyombo',
    'Noto Sans Sundanese',
    'Noto Sans Syloti Nagri',
    'Noto Sans Symbols',
    'Noto Sans Symbols 2',
    'Noto Sans Syriac',
    'Noto Sans Syriac Eastern',
    'Noto Sans Tagalog',
    'Noto Sans Tagbanwa',
    'Noto Sans Tai Le',
    'Noto Sans Tai Tham',
    'Noto Sans Tai Viet',
    'Noto Sans Takri',
    'Noto Sans Tamil',

    'Noto Sans Tamil Supplement ',

    'Noto Sans Tangsa',
    'Noto Sans TC',
    'Noto Sans Telugu',
    'Noto Sans Thaana',
    'Noto Sans Thai',
    'Noto Sans Thai Looped',
    'Noto Sans Tifinagh',
    'Noto Sans Tirhuta',
    'Noto Sans Ugaritic',
    'Noto Sans Vai',
    'Noto Sans Wancho',
    'Noto Sans Warang Citi',
    'Noto Sans Yi',

    'Noto Sans Zanabazar Square ',

    'Noto ',
    'Noto  Ahom',
    'Noto  Armenian',
    'Noto  Balinese',
    'Noto  Bengali',
    'Noto  Devanagari',
    'Noto  ',
    'Noto  Dogra',
    'Noto  Ethiopic',
    'Noto  Georgian',
    'Noto  Grantha',
    'Noto  Gujarati',
    'Noto  Gurmukhi',
    'Noto  Hebrew',
    'Noto  HK',
    'Noto  JP',
    'Noto  Kannada',

    'Noto  Khitan Small Script ',

    'Noto  Khmer',
    'Noto  Khojki',
    'Noto  KR',
    'Noto  Lao',
    'Noto  Makasar',
    'Noto  Malayalam',
    'Noto  Myanmar',
    'Noto  NP Hmong',
    'Noto  Oriya',
    'Noto  Ottoman Siyaq',
    'Noto  SC',
    'Noto  Sinhala',
    'Noto  Tamil',
    'Noto  Tangut',
    'Noto  TC',
    'Noto  Telugu',
    'Noto  Thai',
    'Noto  Tibetan',
    'Noto  Toto',
    'Noto  Yezidi',
    'Noto Traditional Nushu',
    'Nova Cut',
    'Nova Flat',
    'Nova Mono',
    'Nova Oval',
    'Nova Round',
    'Nova Script',
    'Nova Slim',
    'Nova Square',
    'NTR',
    'Numans',
    'Nunito',
    'Nunito Sans',
    'Nuosu SIL',
    'Odibee Sans',
    'Odor Mean Chey',
    'Offside',
    'Oi',
    'Old Standard TT',
    'Oldenburg',
    'Ole',
    'Oleo Script',
    'Oleo Script Swash Caps',
    'Oooh Baby',
    'Open Sans',
    'Oranienbaum',
    'Orbit',
    'Orbitron',
    'Oregano',
    'Orelega One',
    'Orienta',
    'Original Surfer',
    'Oswald',
    'Outfit',
    'Over the Rainbow',
    'Overlock',
    'Overlock SC',
    'Overpass',
    'Overpass Mono',
    'Ovo',
    'Oxanium',
    'Oxygen',
    'Oxygen Mono',
    'Pacifico',
    'Padauk',
    'Padyakke Expanded One',
    'Palanquin',
    'Palanquin Dark',
    'Palette Mosaic',
    'Pangolin',
    'Paprika',
    'Parisienne',
    'Passero One',
    'Passion One',
    'Passions Conflict',
    'Pathway Extreme',
    'Pathway Gothic One',
    'Patrick Hand',
    'Patrick Hand SC',
    'Pattaya',
    'Patua One',
    'Pavanam',
    'Paytone One',
    'Peddana',
    'Peralta',
    'Permanent Marker',
    'Petemoss',
    'Petit Formal Script',
    'Petrona',
    'Philosopher',
    'Phudu',
    'Piazzolla',
    'Piedra',
    'Pinyon Script',
    'Pirata One',
    'Plaster',
    'Play',
    'Playball',
    'Playfair',
    'Playfair ',
    'Playfair  SC',
    'Plus Jakarta Sans',
    'Podkova',
    'Poiret One',
    'Poller One',
    'Poltawski Nowy',
    'Poly',
    'Pompiere',
    'Pontano Sans',
    'Poor Story',
    'Poppins',
    'Port Lligat Sans',
    'Port Lligat Slab',
    'Potta One',
    'Pragati Narrow',
    'Praise',
    'Prata',
    'Preahvihear',
    'Press Start 2P',
    'Pridi',
    'Princess Sofia',
    'Prociono',
    'Prompt',
    'Prosto One',
    'Proza Libre',
    'PT Mono',
    'PT Sans',
    'PT Sans Caption',
    'PT Sans Narrow',
    'PT ',
    'PT  Caption',
    'Public Sans',
    'Puppies Play',
    'Puritan',
    'Purple Purse',
    'Qahiri',
    'Quando',
    'Quantico',
    'Quattrocento',
    'Quattrocento Sans',
    'Questrial',
    'Quicksand',
    'Quintessential',
    'Qwigley',
    'Qwitcher Grypen',
    'Racing Sans One',
    'Radio Canada',
    'Radley',
    'Rajdhani',
    'Rakkas',
    'Raleway',
    'Raleway Dots',
    'Ramabhadra',
    'Ramaraja',
    'Rambla',
    'Rammetto One',
    'Rampart One',
    'Ranchers',
    'Rancho',
    'Ranga',
    'Rasa',
    'Rationale',
    'Ravi Prakash',
    'Readex Pro',
    'Recursive',
    'Red Hat ',
    'Red Hat Mono',
    'Red Hat Text',
    'Red Rose',
    'Redacted',
    'Redacted Script',
    'Redressed',
    'Reem Kufi',
    'Reem Kufi Fun',
    'Reem Kufi Ink',
    'Reenie Beanie',
    'Reggae One',
    'Revalia',
    'Rhodium Libre',
    'Ribeye',
    'Ribeye Marrow',
    'Righteous',
    'Risque',
    'Road Rage',
    'Roboto',
    'Roboto Condensed',
    'Roboto Flex',
    'Roboto Mono',
    'Roboto ',
    'Roboto Slab',
    'Rochester',
    'Rock 3D',
    'Rock Salt',
    'RocknRoll One',
    'Rokkitt',
    'Romanesco',
    'Ropa Sans',
    'Rosario',
    'Rosarivo',
    'Rouge Script',
    'Rowdies',
    'Rozha One',
    'Rubik',
    'Rubik 80s Fade',
    'Rubik Beastly',
    'Rubik Bubbles',
    'Rubik Burned',
    'Rubik Dirt',
    'Rubik Distressed',
    'Rubik Gemstones',
    'Rubik Glitch',
    'Rubik Iso',
    'Rubik Marker Hatch',
    'Rubik Maze',
    'Rubik Microbe',
    'Rubik Mono One',
    'Rubik Moonrocks',
    'Rubik Pixels',
    'Rubik Puddles',
    'Rubik Spray Paint',
    'Rubik Storm',
    'Rubik Vinyl',
    'Rubik Wet Paint',
    'Ruda',
    'Rufina',
    'Ruge Boogie',
    'Ruluko',
    'Rum Raisin',
    'Ruslan ',
    'Russo One',
    'Ruthie',
    'Rye',
    'Sacramento',
    'Sahitya',
    'Sail',
    'Saira',
    'Saira Condensed',
    'Saira Extra Condensed',
    'Saira Semi Condensed',
    'Saira Stencil One',
    'Salsa',
    'Sanchez',
    'Sancreek',
    'Sansita',
    'Sansita Swashed',
    'Sarabun',
    'Sarala',
    'Sarina',
    'Sarpanch',
    'Sassy Frass',
    'Satisfy',
    'Sawarabi Gothic',
    'Sawarabi Mincho',
    'Scada',
    'Scheherazade New',
    'Schibsted Grotesk',
    'Schoolbell',
    'Scope One',
    'Seaweed Script',
    'Secular One',
    'Sedgwick Ave',
    'Sedgwick Ave ',
    'Sen',
    'Send Flowers',
    'Sevillana',
    'Seymour One',
    'Shadows Into Light',
    'Shadows Into Light Two',
    'Shalimar',
    'Shantell Sans',
    'Shanti',
    'Share',
    'Share Tech',
    'Share Tech Mono',
    'Shippori Antique',
    'Shippori Antique B1',
    'Shippori Mincho',
    'Shippori Mincho B1',
    'Shizuru',
    'Shojumaru',
    'Short Stack',
    'Shrikhand',
    'Siemreap',
    'Sigmar',
    'Sigmar One',
    'Signika',
    'Signika Negative',
    'Silkscreen',
    'Simonetta',
    'Single Day',
    'Sintony',
    'Sirin Stencil',
    'Six Caps',
    'Skranji',
    'Slabo 13px',
    'Slabo 27px',
    'Slackey',
    'Slackside One',
    'Smokum',
    'Smooch',
    'Smooch Sans',
    'Smythe',
    'Sniglet',
    'Snippet',
    'Snowburst One',
    'Sofadi One',
    'Sofia',
    'Sofia Sans',
    'Sofia Sans Condensed',
    'Sofia Sans Extra Condensed ',
    'Sofia Sans Semi Condensed ',
    'Solitreo',
    'Solway',
    'Song Myung',
    'Sono',
    'Sonsie One',
    'Sora',
    'Sorts Mill Goudy',
    'Source Code Pro',
    'Source Sans 3',
    'Source  4',
    'Space Grotesk',
    'Space Mono',
    'Special Elite',
    'Spectral',
    'Spectral SC',
    'Spicy Rice',
    'Spinnaker',
    'Spirax',
    'Splash',
    'Spline Sans',
    'Spline Sans Mono',
    'Squada One',
    'Square Peg',
    'Sree Krushnadevaraya',
    'Sriracha',
    'Srisakdi',
    'Staatliches',
    'Stalemate',
    'Stalinist One',
    'Stardos Stencil',
    'Stick',
    'Stick No Bills',
    'Stint Ultra Condensed',
    'Stint Ultra Expanded',
    'STIX Two Text',
    'Stoke',
    'Strait',
    'Style Script',
    'Stylish',
    'Sue Ellen Francisco',
    'Suez One',
    'Sulphur Point',
    'Sumana',
    'Sunflower',
    'Sunshiney',
    'Supermercado One',
    'Sura',
    'Suranna',
    'Suravaram',
    'Suwannaphum',
    'Swanky and Moo Moo',
    'Syncopate',
    'Syne',
    'Syne Mono',
    'Syne Tactile',
    'Tai Heritage Pro',
    'Tajawal',
    'Tangerine',
    'Tapestry',
    'Taprom',
    'Tauri',
    'Taviraj',
    'Teko',
    'Tektur',
    'Telex',
    'Tenali Ramakrishna',
    'Tenor Sans',
    'Text Me One',
    'Texturina',
    'Thasadith',
    'The Girl Next Door',
    'The Nautigal',
    'Tienne',
    'Tillana',
    'Tilt Neon',
    'Tilt Prism',
    'Tilt Warp',
    'Timmana',
    'Tinos',
    'Tiro Bangla',
    'Tiro Devanagari Hindi',
    'Tiro Devanagari Marathi',
    'Tiro Devanagari Sanskrit',
    'Tiro Gurmukhi',
    'Tiro Kannada',
    'Tiro Tamil',
    'Tiro Telugu',
    'Titan One',
    'Titillium Web',
    'Tomorrow',
    'Tourney',
    'Trade Winds',
    'Train One',
    'Trirong',
    'Trispace',
    'Trocchi',
    'Trochut',
    'Truculenta',
    'Trykker',
    'Tsukimi Rounded',
    'Tulpen One',
    'Turret Road',
    'Twinkle Star',
    'Ubuntu',
    'Ubuntu Condensed',
    'Ubuntu Mono',
    'Uchen',
    'Ultra',
    'Unbounded',
    'Uncial Antiqua',
    'Underdog',
    'Unica One',
    'UnifrakturCook',
    'UnifrakturMaguntia',
    'Unkempt',
    'Unlock',
    'Unna',
    'Updock',
    'Urbanist',
    'Vampiro One',
    'Varela',
    'Varela Round',
    'Varta',
    'Vast Shadow',
    'Vazirmatn',
    'Vesper Libre',
    'Viaoda Libre',
    'Vibes',
    'Vibur',
    'Victor Mono',
    'Vidaloka',
    'Viga',
    'Vina Sans',
    'Voces',
    'Volkhov',
    'Vollkorn',
    'Vollkorn SC',
    'Voltaire',
    'VT323',
    'Vujahday Script',
    'Waiting for the Sunrise',
    'Wallpoet',
    'Walter Turncoat',
    'Warnes',
    'Water Brush',
    'Waterfall',
    'Wellfleet',
    'Wendy One',
    'Whisper',
    'WindSong',
    'Wire One',
    'Wix Madefor ',
    'Wix Madefor Text',
    'Work Sans',
    'Xanh Mono',
    'Yaldevi',
    'Yanone Kaffeesatz',
    'Yantramanav',
    'Yatra One',
    'Yellowtail',
    'Yeon Sung',
    'Yeseva One',
    'Yesteryear',
    'Yomogi',
    'Yrsa',
    'Ysabeau',
    'Ysabeau Infant',
    'Ysabeau Office',
    'Ysabeau SC',
    'Yuji Boku',
    'Yuji Hentaigana Akari',
    'Yuji Hentaigana Akebono',
    'Yuji Mai',
    'Yuji Syuku',
    'Yusei Magic',
    'ZCOOL KuaiLe',
    'ZCOOL QingKe HuangYou',
    'ZCOOL XiaoWei',
    'Zen Antique',
    'Zen Antique Soft',
    'Zen Dots',
    'Zen Kaku Gothic Antique',
    'Zen Kaku Gothic New',
    'Zen Kurenaido',
    'Zen Loop',
    'Zen Maru Gothic',
    'Zen Old Mincho',
    'Zen Tokyo Zoo',
    'Zeyada',
    'Zhi Mang Xing',
    'Zilla Slab',
    'Zilla Slab Highlight',
];

export const alignmentValues = [
    'normal',
    'start',
    'center',
    'end',
    'flex-start',
    'flex-end',
    'baseline',
    'first baseline',
    'last baseline',
    'space-between',
    'space-around',
    'space-evenly',
    'stretch',
    'safe center',
    'unsafe center',
];

export const properties = {
    'align-content': [...alignmentValues],
    'align-items': [...alignmentValues],
    'align-self': [
        'auto',
        'anchor-center',
        ...alignmentValues,
    ],
    all: [...globalValues],
    /* anchor-name */
    /* animation-* */
    appearance: [
        'none',
        'auto',
        'menulist-button',
        'textfield',
        'button',
        'checkbox',
        'listbox ',
        'menulist',
        'meter',
        'progress-bar',
        'push-button',
        'radio',
        'searchfield',
        'slider-horizontal',
        'square-button',
        'textarea',
    ],
    'aspect-ratio': [
        '1/1',
        '14/9',
        '16/10',
        '16/9',
        '185/100',
        '2/1',
        '239/100',
        '4/3',
        '1,',
    ],
    'backgdrop-filter': [],
    'backface-visibility': [
        'visible',
        'hidden',
    ],
    /* background-* */
    'background-attachment': [
        'scroll',
        'fixed',
        'local',
    ],
    'background-blend-mode': [
        'normal',
        'multiply',
        'screen',
        'overlay',
        'darken',
        'lighten',
        'color-dodge',
        'color-burn',
        'hard-light',
        'soft-light',
        'difference',
        'exclusion',
        'hue',
        'saturation',
        'color',
        'luminosity',
    ],
    'background-clip': [
        'border-box',
        'padding-box',
        'content-box',
        'text',
    ],
    'background-color': [...colors],
    'background-image': [],
    'background-origin': [
        'border-box',
        'padding-box',
        'content-box',
    ],
    'background-position': [
        'top',
        'bottom',
        'left',
        'right',
        'center',
        'top left',
        'top center',
        'top right',
        'left center',
        'right center',
        'bottom left',
        'bottom center',
        'bottom right',
    ],
    'background-position-x': [
        'left',
        'center',
        'right',
    ],
    'background-position-y': [
        'top',
        'center',
        'bottom',
    ],
    'background-repeat': [
        'repeat',
        'repeat-x',
        'repeat-y',
        'space',
        'round',
        'no-repeat',
    ],
    'background-size': [
        'cover',
        'contain',
        'auto',
    ],
    'block-size': [],
    'baseline-shift': [],
    'block-step': [],
    'block-step-align': [],
    'block-step-insert': [],
    'block-step-round': [],
    'block-step-size': [],
    'bookmark-label': [],
    'bookmark-level': [],
    'bookmark-state': [],

    'border': [],

    'border-block': [],
    'border-block-color': [],
    'border-block-end': [],
    'border-block-end-color': [],
    'border-block-end-style': [],
    'border-block-end-width': [],
    'border-block-start': [],
    'border-block-start-color': [],
    'border-block-start-style': [],
    'border-block-start-width': [],
    'border-block-style': [],
    'border-block-width': [],

    'border-bottom': [
        'none',
    ],
    'border-bottom-color': [...colors],
    'border-bottom-left-radius': [...borderRadii],
    'border-bottom-right-radius': [...borderRadii],
    'border-bottom-style': [...borderStyles],
    'border-bottom-width': [...borderWidths],

    'border-boundary': [],
    'border-collapse': [
        'collapse',
        'separate',
    ],
    'border-color': [...colors],

    'border-image': [],
    'border-image-outset': [],
    'border-image-repeat': [],
    'border-image-slice': [],
    'border-image-source': [],
    'border-image-width': [],

    'border-inline': [],
    'border-inline-color': [],
    'border-inline-end': [],
    'border-inline-end-color': [],
    'border-inline-end-style': [],
    'border-inline-end-width': [],
    'border-inline-start': [],
    'border-inline-start-color': [],
    'border-inline-start-style': [],
    'border-inline-start-width': [],
    'border-inline-style': [],
    'border-inline-width': [],

    'border-left': ['none'],
    'border-left-color': [...colors],
    'border-left-style': [...borderStyles],
    'border-left-width': [...borderWidths],

    'border-radius': [...borderRadii],

    'border-right': ['none'],
    'border-right-color': [...colors],
    'border-right-style': [...borderStyles],
    'border-right-width': [...borderWidths],

    'border-spacing': [],

    'border-start-end-radius': [],
    'border-start-start-radius': [],

    'border-style': [...borderStyles],
    'border-top': ['none'],
    'border-top-color': [...colors],
    'border-top-left-radius': [...borderRadii],
    'border-top-right-radius': [...borderRadii],
    'border-top-style': [...borderStyles],
    'border-top-width': [...borderWidths],
    'border-width': [...borderWidths],

    'bottom': [...positionDistances],

    'box-decoration-break': [],

    'box-shadow': [
        'none',
        ...boxShadows,
    ],
    'box-sizing': [
        'border-box',
        'content-box',
    ],
    'box-snap': [],
    'break-after': [],
    'break-before': [],
    'break-inside': [],
    'caption-side': [
        'top',
        'bottom',
    ],
    'caret': [],
    'caret-animation': [],
    'caret-color': [],
    'caret-shape': [],
    'chains': [],
    'clear': [
        'none',
        'both',
        'left',
        'right',
        'inline-start',
        'inline-end',
    ],
    'clip': [],
    'clip-path': [
        'circle(10%)',
        'circle(20%)',
        'circle(30%)',
        'circle(40%)',
        'circle(50%)',
        'circle(60%)',
        'circle(70%)',
        'circle(80%)',
        'circle(90%)',
        'margin-box',
        'border-box',
        'padding-box',
        'content-box',
        'fill-box',
        'stroke-box',
        'view-box',
        'none',
    ],
    'clip-rule': [],
    'color': [...colors],
    'color-adjust': [],
    'color-interpolation-filters': [],
    'color-scheme': [
        'dark',
        'light dark',
        'light',
        'normal',
        'only dark',
        'only light',
    ],
    'column-count': [
        'auto',
        '1',
        '2',
        '3',
        '4',
    ],
    'column-fill': [
        'auto',
        'balance',
        'balance-all',
    ],
    'column-gap': [...gapDistances],
    'column-rule': [],
    'column-rule-color': [...colors],
    'column-rule-style': [...borderStyles],
    'column-rule-width': [...borderWidths],
    'column-span': [
        'none',
        'all',
    ],
    'column-width': [
        ...widthsAndHeights,
    ],
    'columns': [],
    'contain': [],
    'content': [
        '" "',
        '","',
        '":"',
        '"|"',
        '"/"',
    ],
    'continue': [],
    'counter-increment': [],
    'counter-reset': [],
    'counter-set': [],
    'cue': [],
    'cue-after': [],
    'cue-before': [],
    'cursor': [
        'auto',
        'alias',
        'all-scroll',
        'auto',
        'cell',
        'col-resize',
        'context-menu',
        'copy',
        'crosshair',
        'default',
        'e-resize',
        'ew-resize',
        'grab',
        'grabbing',
        'help',
        'move',
        'n-resize',
        'ne-resize',
        'nesw-resize',
        'no-drop',
        'none',
        'not-allowed',
        'ns-resize',
        'nw-resize',
        'nwse-resize',
        'pointer',
        'progress',
        'row-resize',
        's-resize',
        'se-resize',
        'sw-resize',
        'text',
        'vertical-text',
        'w-resize',
        'wait',
        'zoom-in',
        'zoom-out',
    ],
    'direction': [
        'ltr',
        'rtl',
    ],
    'display': [
        'block flex',
        'block flow-root',
        'block flow',
        'block grid',
        'block',
        'contents',
        'flex',
        'flow-root',
        'grid',
        'inline flex',
        'inline flow-root',
        'inline flow',
        'inline grid',
        'inline-block',
        'inline-flex',
        'inline-grid',
        'inline',
        'list-item',
        'none',
        'table-row',
        'table',
    ],
    'dominant-baseline': [],
    'elevation': [],
    'empty-cells': [],
    'filter': [
        ...filters,
    ],
    'flex': [],
    'flex-basis': [
        ...widthsAndHeights,
        'max-content',
        'min-content',
        'fit-content',
    ],
    'flex-direction': [
        'row',
        'row-reverse',
        'column',
        'column-reverse',
    ],
    'flex-flow': [
        'row',
        'row-reverse',
        'column',
        'column-reverse',
        'nowrap',
        'wrap',
        'wrap-reverse',
        'row nowrap',
        'column wrap',
        'column-reverse wrap-reverse',
    ],
    'flex-grow': [
        '1',
        '0',
    ],
    'flex-shrink': [
        '1',
        '0',
    ],
    'flex-wrap': [
        'nowrap',
        'wrap',
        'wrap-reverse',
    ],
    'float': [
        'left',
        'right',
        'none',
        'inline-start',
        'inline-end',
    ],
    'float-defer': [],
    'float-offset': [],
    'float-reference': [],
    'flood-color': [],
    'flood-opacity': [],
    'flow': [],
    'flow-from': [],
    'flow-into': [],
    'font': [],
    'font-family': [
        'cursive',
        'emoji',
        'fangsong',
        'fantasy',
        'math',
        'monospace',
        'sans-serif',
        'serif',
        'system-ui',
        'ui-monospace',
        'ui-rounded',
        'ui-sans-serif',
        'ui-serif',
        {
            'system-font-stack':
                '-apple-system, BlinkMacSystemFont, avenir next, avenir, segoe ui, helvetica neue, helvetica, Cantarell, Ubuntu, roboto, noto, arial, sans-serif',
        },
    ],
    'font-feature-settings': [],
    'font-kerning': [
        'auto',
        'normal',
        'none',
    ],
    'font-language-override': [],
    'font-optical-sizing': [
        'none',
        'auto',
    ],
    'font-size': [...fontSizes],
    'font-size-adjust': [],
    'font-stretch': [],
    'font-style': [
        'normal',
        'italic',
        'oblique',
    ],
    'font-synthesis': [],
    'font-variant': [],
    'font-variant-alternates': [],
    'font-variant-caps': [],
    'font-variant-east-asian': [],
    'font-variant-ligatures': [],
    'font-variant-numeric': [],
    'font-variant-position': [],
    'font-weight': [
        'normal',
        'bold',
        '100',
        '200',
        '300',
        '400',
        '450',
        '500',
        '600',
        '700',
        '800',
        '900',
        'lighter',
        'bolder',
    ],
    'footnote-display': [],
    'footnote-policy': [],
    'glyph-orientation-vertical': [],
    'gap': [...gapDistances],
    'grid': [],
    'grid-area': [
        'a',
        'b',
        'c',
        'd',
        'e',
        'f',
        'g',
        'h',
        'i',
        'j',
        'k',
        'l',
        'm',
        'n',
        'o',
        'p',
        'q',
        'r',
        's',
        't',
        'u',
        'v',
        'w',
        'x',
        'y',
        'z',
    ],
    'grid-auto-columns': [
        'min-content',
        'max-content',
        'auto',
    ],
    'grid-auto-flow': [
        'row',
        'column',
        'dense',
        'row dense',
        'column dense',
    ],
    'grid-auto-rows': [
        'min-content',
        'max-content',
        'auto',
    ],
    'grid-column': [],
    'grid-column-end': [
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '24',
    ],
    'grid-column-gap': [...gapDistances],
    'grid-column-start': [
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '24',
    ],
    'grid-gap': [...gapDistances],
    'grid-row': [],
    'grid-row-end': [
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '24',
    ],
    'grid-row-gap': [...gapDistances],
    'grid-row-start': [
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '24',
    ],
    'grid-template': [],
    'grid-template-areas': [
        { 'one-column-layout': "'a' 'b' 'c' 'd' 'e' 'f'" },
        { 'two-column-layout': "'a a' 'b b' 'c d' 'e e' 'f f'" },
        { 'three-column-layout': "'a a a' 'b b b' 'c d e' 'f f f' 'g g g'" },
    ],
    'grid-template-columns': [...gridTracks],
    'grid-template-rows': [...gridTracks],
    'hanging-punctuation': [],
    'height': [...widthsAndHeights],
    'hyphenate-character': [],
    'hyphenate-limit-chars': [],
    'hyphenate-limit-last': [],
    'hyphenate-limit-lines': [],
    'hyphenate-limit-zone': [],
    'hyphens': [],
    'image-orientation': [],
    'image-rendering': [],
    'image-resolution': [],
    'initial-letter': [],
    'initial-letter-align': [],
    'initial-letter-wrap': [],
    'isolation': [],
    'justify-content': [
        'center',
        'start',
        'end',
        'flex-start',
        'flex-end',
        'left',
        'right',
        'normal',
        'space-between',
        'space-around',
        'space-evenly',
        'stretch',
        'safe center',
        'unsafe center',
    ],
    'justify-items': [
        'normal',
        'stretch',
        'center',
        'start',
        'end',
        'flex-start',
        'flex-end',
        'self-start',
        'self-end',
        'left',
        'right',
        'anchor-center',
        'baseline',
        'first baseline',
        'last baseline',
        'safe center',
        'unsafe center',
        'legacy right',
        'legacy left',
        'legacy center',
    ],
    'justify-self': [
        'auto',
        'normal',
        'stretch',
        'center',
        'start',
        'end',
        'flex-start',
        'flex-end',
        'self-start',
        'self-end',
        'left',
        'right',
        'anchor-center',
        'baseline',
        'first baseline',
        'last baseline',
        'safe center',
        'unsafe center',
        'legacy right',
        'legacy left',
        'legacy center',
    ],
    'left': [...positionDistances],
    'letter-spacing': [
        'normal',
        '-0.3em',
        '-0.2em',
        '-0.1em',
        '-0.05em',
        '0.3em',
        '0.2em',
        '0.1em',
        '0.05em',
    ],
    'lighting-color': [],
    'line-break': [
        'auto',
        'loose',
        'normal',
        'strict',
        'anywhere',
    ],
    'line-grid': [],
    'line-height': [
        'normal',
        '1',
        '1.2',
        '1.25',
        '1.33',
        '1.5',
        '1.6',
        '1.7',
        '1.75',
        '1.8',
        '1.875',
        '2',
        '2.2',
        '2.25',
        '2.33',
        '2.5',
        '2.6',
        '2.7',
        '2.75',
        '2.8',
        '2.875',
        '3',
        '8px',
        '9px',
        '10px',
        '12px',
        '14px',
        '16px',
        '18px',
        '20px',
        '22px',
        '24px',
        '26px',
        '28px',
        '30px',
        '32px',
        '34px',
        '36px',
        '38px',
        '40px',
        '42px',
        '.25rem',
        '.5rem',
        '.75rem',
        '.875rem',
        '1rem',
        '1.25rem',
        '1.5rem',
        '1.75rem',
        '1.875rem',
        '2rem',
        '2.25rem',
        '2.5rem',
        '2.75rem',
        '2.875rem',
        '3rem',
        '4rem',
        '5rem',
    ],
    'line-height-step': [],
    'line-snap': [],
    'list-style': [
        'none',
    ],
    'list-style-image': [],
    'list-style-position': [
        'inside',
        'outside',
    ],
    'list-style-type': [
        'none',
        'disc',
        'circle',
        'square',
        'decimal',
        'decimal-leading-zero',
        'lower-roman',
        'upper-roman',
        'lower-greek',
        'lower-alpha',
        'lower-latin',
        'upper-alpha',
        'upper-latin',
        { dash: '"-"' },
        { asterisk: '"*"' },
    ],
    'margin': [...gapDistances],
    'margin-bottom': [...gapDistances],
    'margin-left': [...gapDistances],
    'margin-right': [...gapDistances],
    'margin-top': [...gapDistances],
    'marker': [],
    'marker-end': [],
    'marker-knockout-left': [],
    'marker-knockout-right': [],
    'marker-mid': [],
    'marker-pattern': [],
    'marker-segment': [],
    'marker-side': [],
    'marker-start': [],
    'marquee-direction': [],
    'marquee-loop': [],
    'marquee-speed': [],
    'marquee-style': [],
    'mask': [],
    'mask-border': [],
    'mask-border-mode': [],
    'mask-border-outset': [],
    'mask-border-repeat': [],
    'mask-border-slice': [],
    'mask-border-source': [],
    'mask-border-width': [],
    'mask-clip': [],
    'mask-composite': [],
    'mask-image': [],
    'mask-mode': [],
    'mask-origin': [],
    'mask-position': [],
    'mask-repeat': [],
    'mask-size': [],
    'mask-type': [],
    'max-height': [...widthsAndHeights],
    'max-lines': [],
    'max-width': [...widthsAndHeights],
    'min-height': [...widthsAndHeights],
    'min-width': [...widthsAndHeights],
    'mix-blend-mode': [
        'normal',
        'multiply',
        'screen',
        'overlay',
        'darken',
        'lighten',
        'color-dodge',
        'color-burn',
        'hard-light',
        'soft-light',
        'difference',
        'exclusion',
        'hue',
        'saturation',
        'color',
        'luminosity',
        'plus-darker',
        'plus-lighter',
    ],
    'motion': [],
    'motion-offset': [],
    'motion-path': [],
    'motion-rotation': [],
    'nav-down': [],
    'nav-left': [],
    'nav-right': [],
    'nav-up': [],
    'object-fit': [
        'contain',
        'cover',
        'fill',
        'none',
        'scale-down',
    ],
    'object-position': [
        'top',
        'bottom',
        'left',
        'right',
        'center',
    ],
    'offset': [],
    'offset-after': [],
    'offset-anchor': [],
    'offset-before': [],
    'offset-distance': [],
    'offset-end': [],
    'offset-path': [],
    'offset-position': [],
    'offset-rotate': [],
    'offset-start': [],
    'opacity': [
        '.9',
        '.8',
        '.7',
        '.6',
        '.5',
        '.4',
        '.3',
        '.2',
        '.1',
    ],
    'order': [
        '-1',
        '-2',
        '-3',
        '-4',
        '-5',
        '-6',
        '-7',
        '-8',
        '-9',
        '-10',
        '0',
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
    ],
    'orphans': [
        '0',
        '1',
        '2',
        '3',
        '4',
        '5',
    ],
    'outline': ['none'],
    'outline-color': [...colors],
    'outline-offset': [...widthsAndHeights],
    'outline-style': [...borderStyles],
    'outline-width': [...borderWidths],
    'overflow': [
        'visible',
        'hidden',
        'clip',
        'scroll',
        'auto',
    ],
    'overflow-style': [],
    'overflow-wrap': [
        'normal',
        'break-word',
        'anywhere',
    ],
    'overflow-x': [
        'visible',
        'hidden',
        'clip',
        'scroll',
        'auto',
    ],
    'overflow-y': [
        'visible',
        'hidden',
        'clip',
        'scroll',
        'auto',
    ],
    'padding': [...gapDistances],
    'padding-bottom': [...gapDistances],
    'padding-left': [...gapDistances],
    'padding-right': [...gapDistances],
    'padding-top': [...gapDistances],
    'page': [],
    'page-break-after': [],
    'page-break-before': [],
    'page-break-inside': [],
    'pause': [],
    'pause-after': [],
    'pause-before': [],
    'perspective': [],
    'perspective-origin': [],
    'pitch': [],
    'pitch-range': [],
    'place-content': [],
    'place-items': [],
    'place-self': [],
    'play-during': [],
    'position': [
        'static',
        'relative',
        'absolute',
        'fixed',
        'sticky',
    ],
    'presentation-level': [],
    'quotes': [],
    'region-fragment': [],
    'resize': [
        'none',
        'both',
        'horizontal',
        'vertical',
        'block',
        'inline',
    ],
    'rest': [],
    'rest-after': [],
    'rest-before': [],
    'richness': [],
    'right': [...positionDistances],
    'rotate': [
        '0deg',
        '100deg',
        '105deg',
        '10deg',
        '110deg',
        '115deg',
        '120deg',
        '125deg',
        '130deg',
        '135deg',
        '140deg',
        '145deg',
        '150deg',
        '155deg',
        '15deg',
        '160deg',
        '165deg',
        '170deg',
        '175deg',
        '180deg',
        '185deg',
        '190deg',
        '195deg',
        '200deg',
        '205deg',
        '20deg',
        '210deg',
        '215deg',
        '220deg',
        '225deg',
        '230deg',
        '235deg',
        '240deg',
        '245deg',
        '250deg',
        '255deg',
        '25deg',
        '260deg',
        '265deg',
        '270deg',
        '275deg',
        '280deg',
        '285deg',
        '290deg',
        '295deg',
        '300deg',
        '305deg',
        '30deg',
        '310deg',
        '315deg',
        '320deg',
        '325deg',
        '330deg',
        '335deg',
        '340deg',
        '345deg',
        '350deg',
        '355deg',
        '35deg',
        '360deg',
        '40deg',
        '45deg',
        '50deg',
        '55deg',
        '5deg',
        '60deg',
        '65deg',
        '70deg',
        '75deg',
        '80deg',
        '85deg',
        '90deg',
        '95deg',
    ],
    'rotation-point': [],
    'ruby-align': [],
    'ruby-merge': [],
    'ruby-position': [],
    'running': [],
    'scroll-behavior': [],
    'scroll-padding': [],
    'scroll-padding-block': [],
    'scroll-padding-block-end': [],
    'scroll-padding-block-start': [],
    'scroll-padding-bottom': [],
    'scroll-padding-inline': [],
    'scroll-padding-inline-end': [],
    'scroll-padding-inline-start': [],
    'scroll-padding-left': [],
    'scroll-padding-right': [],
    'scroll-padding-top': [],
    'scroll-snap-align': [],
    'scroll-snap-margin': [],
    'scroll-snap-margin-block': [],
    'scroll-snap-margin-block-end': [],
    'scroll-snap-margin-block-start': [],
    'scroll-snap-margin-bottom': [],
    'scroll-snap-margin-inline': [],
    'scroll-snap-margin-inline-end': [],
    'scroll-snap-margin-inline-start': [],
    'scroll-snap-margin-left': [],
    'scroll-snap-margin-right': [],
    'scroll-snap-margin-top': [],
    'scroll-snap-stop': [],
    'scroll-snap-type': [],
    'scrollbar-gutter': [],
    'shape-image-threshold': [],
    'shape-inside': [],
    'shape-margin': [],
    'shape-outside': [],
    'size': [],
    'speak': [],
    'speak-as': [],
    'speak-header': [],
    'speak-numeral': [],
    'speak-punctuation': [],
    'speech-rate': [],
    'stress': [],
    'string-set': [],
    'stroke': [],
    'stroke-alignment': [],
    'stroke-dashadjust': [],
    'stroke-dasharray': [],
    'stroke-dashcorner': [],
    'stroke-dashoffset': [],
    'stroke-linecap': [],
    'stroke-linejoin': [],
    'stroke-miterlimit': [],
    'stroke-opacity': [],
    'stroke-width': [],
    'tab-size': [],
    'table-layout': [],
    'text-align': [
        'start',
        'end',
        'left',
        'right',
        'center',
        'justify',
        'justify-all',
        'match-parent',
    ],
    'text-align-all': [],
    'text-align-last': [],
    'text-combine-upright': [],
    'text-decoration': [],
    'text-decoration-color': [...colors],
    'text-decoration-line': [
        'none',
        'underline',
        'overline',
        'line-through',
        'blink',
    ],
    'text-decoration-skip': [],
    'text-decoration-style': [
        'solid',
        'double',
        'dotted',
        'dashed',
        'wavy',
    ],
    'text-decoration-thickness': [
        'auto',
        'from-font',
        ...borderWidths,
    ],
    'text-emphasis': [],
    'text-emphasis-color': [],
    'text-emphasis-position': [],
    'text-emphasis-style': [],
    'text-indent': [
        '.25rem',
        '.5rem',
        '.75rem',
        '.875rem',
        '1rem',
        '1.25rem',
        '1.5rem',
        '1.75rem',
        '1.875rem',
        '2rem',
    ],
    'text-justify': [
        'none',
        'auto',
        'inter-word',
        'inter-character',
    ],
    'text-orientation': [
        'mixed',
        'upright',
        'sideways-right',
        'sideways',
        'use-glyph-orientation',
    ],
    'text-overflow': [
        'clip',
        'ellipsis',
    ],
    'text-shadow': [
        'none',
        ...textShadows,
    ],
    'text-space-collapse': [],
    'text-space-trim': [],
    'text-spacing': [],
    'text-transform': [
        'none',
        'capitalize',
        'uppercase',
        'lowercase',
        'full-width',
    ],
    'text-underline-offset': [
        '-1px',
        '-2px',
        '-3px',
        '-4px',
        '-5px',
        '0px',
        '1px',
        '2px',
        '3px',
        '4px',
        '5px',
        '6px',
        '7px',
        '8px',
        '9px',
        '10px',
        '.25rem',
        '.5rem',
        '.75rem',
        '.875rem',
        '1rem',
        '1.25rem',
        '1.5rem',
        '1.75rem',
        '1.875rem',
        '2rem',
        'auto',
    ],
    'text-underline-position': [],
    'text-wrap': [
        'wrap',
        'nowrap',
        'balance',
        'pretty',
        'stable',
    ],
    'top': [...widthsAndHeights],
    'transform': [],
    'transform-box': [],
    'transform-origin': [],
    'transform-style': [],
    'transition': [],
    'transition-delay': [],
    'transition-duration': [],
    'transition-property': [],
    'transition-timing-function': [],
    'unicode-bidi': [],
    'user-select': [],
    'vertical-align': [
        'baseline',
        'sub',
        'super',
        'text-top',
        'text-bottom',
        'middle',
        'top',
        'bottom',
    ],
    'visibility': [
        'visible',
        'hidden',
        'collapse',
    ],
    'voice-balance': [],
    'voice-duration': [],
    'voice-family': [],
    'voice-pitch': [],
    'voice-range': [],
    'voice-rate': [],
    'voice-stress': [],
    'voice-volume': [],
    'volume': [],
    'white-space': [
        'normal',
        'nowrap',
        'pre',
        'pre-wrap',
        'pre-line',
        'break-spaces',
        'collapse balance',
        'preserve nowrap',
    ],
    'widows': [
        '0',
        '1',
        '2',
        '3',
        '4',
        '5',
    ],
    'width': [...widthsAndHeights],
    'will-change': [],
    'word-break': [
        'normal',
        'break-all',
        'keep-all',
    ],
    'word-spacing': [
        'normal',
        '-1px',
        '-2px',
        '-3px',
        '-4px',
        '-5px',
        '0px',
        '1px',
        '2px',
        '3px',
        '4px',
        '5px',
        '6px',
        '7px',
        '8px',
        '9px',
        '10px',
        '.25rem',
        '.5rem',
        '.75rem',
        '.875rem',
        '1rem',
        '1.25rem',
        '1.5rem',
        '1.75rem',
        '1.875rem',
        '2rem',
    ],
    'word-wrap': [],
    'wrap-after': [],
    'wrap-before': [],
    'wrap-flow': [],
    'wrap-inside': [],
    'wrap-through': [],
    'writing-mode': [],
    'z-index': [
        '0',
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '20',
        '30',
        '40',
        '50',
        '60',
        '70',
        '80',
        '90',
        '99',
        '999',
        '9999',
    ],
};
